name: expression_cli
description: A sample command-line application with basic argument parsing.
version: 0.2.0
repository: https://github.com/FilledStacks/expression-ui

environment:
  sdk: ^3.3.3

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  collection: ^1.18.0
  expression_ui:
    path: ../expression-ui-flutter
    
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  mustachex: ^1.0.0
  path: ^1.9.0
  recase: ^4.1.0
  rive_common: 0.4.15

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^3.0.3
  json_serializable: ^6.8.0
  lints: ^5.1.1
  test: ^1.24.0

executables:
  expressionui: